name: not_too_shabby
description: Plays a random video from the "Not Too Shabby" YouTube playlist by kisscactus
authors:
  - Tevan Carrell <tevanc14@gmail.com>
version: 0.5.2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  flutter_youtube: ^1.1.4
  http: ^0.12.0
  path_provider: ^0.5.0
  url_launcher: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
