name: not_too_shabby
description: Plays a random video from the "Not Too Shabby" YouTube playlist by kisscactus
authors:
  - Tevan Carrell <tevanc14@gmail.com>
version: 0.19.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  firebase_analytics: ^5.0.11
  firebase_core: ^0.4.3+3
  flutter:
    sdk: flutter
  flutter_youtube: ^2.0.0
  http: ^0.12.0
  path_provider: ^0.5.0
  url_launcher: ^4.0.1

dev_dependencies:
  pedantic: ^1.9.0

flutter:
  assets:
    - assets/
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
  uses-material-design: true
